---
title: 'Characterising the persistence of RT-PCR positivity and incidence in a community survey of SARS-CoV-2'
description: 'Wellcome Open Research 7:102'
author: Oliver Eales, Caroline E. Walters, Haowei Wang, David Haw, Kylie E. C. Ainslie, Christina J. Atchison, Andrew J. Page, Sophie Prosolek, Alexander J. Trotter, hanh Le Viet, Nabil-Fareed Alikhan, Leigh M. Jackson, Catherine Ludden, COVID-19 Genomics UK Consortium, Deborah Ashby, Christl A. Donnelly, Graham Cooke, Wendy Barclay, Helen Ward, Ara Darzi, Paul Elliott, Steven Riley
date: '2022-03-21'
doi: https://doi.org/10.12688/wellcomeopenres.17723.1
categories: 
  - publication
---

# Abstract

**Background**

The REal-time Assessment of Community Transmission-1 (REACT-1) study has provided unbiased estimates of swab-positivity in England approximately monthly since May 2020 using RT-PCR testing of self-administered throat and nose swabs. However, estimating infection incidence requires an understanding of the persistence of RT-PCR swab-positivity in the community.\
**Methods**

During round 8 of REACT-1 from 6 January to 22 January 2021, we collected up to two additional swabs from 896 initially RT-PCR positive individuals approximately 6 and 9 days after their initial swab.\
**Results**

Test sensitivity and duration of positivity were estimated using an exponential decay model, for all participants and for subsets by initial N-gene cycle threshold (Ct) value, symptom status, lineage and age. A P-spline model was used to estimate infection incidence for the entire duration of the REACT-1 study. REACT-1 test sensitivity was estimated at 0.79 (0.77, 0.81) with median duration of positivity at 9.7 (8.9, 10.6) days. We found greater duration of positivity in those exhibiting symptoms, with low N-gene Ct values, or infected with the Alpha variant. Test sensitivity was found to be higher for those who were pre-symptomatic or with low N-gene Ct values. Compared to swab-positivity, our estimates of infection incidence included sharper features with evident transient increases around the time of changes in social distancing measures.\
**Conclusions**

These results validate previous efforts to estimate incidence of SARS-CoV-2 from swab-positivity data and provide a reliable means to obtain community infection estimates to inform policy response.

# Citation

Eales O, Walters CE, Wang H *et al.* Characterising the persistence of RT-PCR positivity and incidence in a community survey of SARS-CoV-2 \[version 1; peer review: 2 approved with reservations\]. *Wellcome Open Res* 2022, **7**:102. [\[DOI\]](https://doi.org/10.12688/wellcomeopenres.17723.1)
