---
title: 'SARS-CoV-2 infection prevalence on repatriation flights from Wuhan City, China'
description: 'Journal of travel medicine 27(8):taaa135'
author: 'Hayley A Thompson, Natsuko Imai, Amy Dighe, et al.'
date: '2021-08-24'
doi: https://doi.org/10.1093/jtm/taaa135
categories: 
  - publication
---

# Citation

Hayley A Thompson, Natsuko Imai, Amy Dighe, Kylie E C Ainslie, Marc Baguelin, Sangeeta Bhatia, Samir Bhatt, Adhiratha Boonyasiri, Olivia Boyd, Nicholas F Brazeau, Lorenzo Cattarino, Laura V Cooper, Helen Coupland, Zulma Cucunuba, Gina Cuomo-Dannenburg, Bimandra Djaafara, Ilaria Dorigatti, Sabine van Elsland, Richard FitzJohn, Han Fu, Katy A M Gaythorpe, Will Green, Timothy Hallett, Arran Hamlet, David Haw, Sarah Hayes, Wes Hinsley, Benjamin Jeffrey, MRes, Edward Knock, Daniel J Laydon, John Lees, Tara D Mangal, Thomas Mellan, Swapnil Mishra, Andria Mousa, MPH, Gemma Nedjati-Gilani, Pierre Nouvellet, Lucy Okell, Kris V Parag, Manon Ragonnet-Cronin, Steven Riley, H Juliette T Unwin, Robert Verity, Michaela Vollmer, Erik Volz, Patrick G T Walker, Caroline Walters, Haowei Wang, Yuanrong Wang, Oliver J Watson, Charles Whittaker, Lilith K Whittles, Peter Winskill, Xiaoyue Xi, Christl A Donnelly, Neil M Ferguson, SARS-CoV-2 infection prevalence on repatriation flights from Wuhan City, China, *Journal of Travel Medicine* 27(8):taaa135. [\[DOI\]](https://doi.org/10.1093/jtm/taaa135)
