---
title: 'Evidence of initial success for China exiting COVID-19 social distancing policy after achieving containment'
description: 'Wellcome Open Research 5: 81'
author: Kylie EC Ainslie, Caroline E Walters, Han Fu, et al.
date: '2020-10-01'
doi: https://doi.org/10.12688/wellcomeopenres.15843.2
categories: 
  - publication
---

# Abstract

## **Background**

The COVID-19 epidemic was declared a Global Pandemic by WHO on 11 March 2020. By 24 March 2020, over 440,000 cases and almost 20,000 deaths had been reported worldwide. In response to the fast-growing epidemic, which began in the Chinese city of Wuhan, Hubei, China imposed strict social distancing in Wuhan on 23 January 2020 followed closely by similar measures in other provinces. These interventions have impacted economic productivity in China, and the ability of the Chinese economy to resume without restarting the epidemic was not clear.

## **Methods**

Using daily reported cases from mainland China and Hong Kong SAR, we estimated transmissibility over time and compared it to daily within-city movement, as a proxy for economic activity.

## **Results**

Initially, within-city movement and transmission were very strongly correlated in the five mainland provinces most affected by the epidemic and Beijing. However, that correlation decreased rapidly after the initial sharp fall in transmissibility. In general, towards the end of the study period, the correlation was no longer apparent, despite substantial increases in within-city movement. A similar analysis for Hong Kong shows that intermediate levels of local activity were maintained while avoiding a large outbreak. At the very end of the study period, when China began to experience the re-introduction of a small number of cases from Europe and the United States, there is an apparent up-tick in transmission.

## **Conclusions**

Although these results do not preclude future substantial increases in incidence, they suggest that after very intense social distancing (which resulted in containment), China successfully exited its lockdown to some degree. Elsewhere, movement data are being used as proxies for economic activity to assess the impact of interventions. The results presented here illustrate how the eventual decorrelation between transmission and movement is likely a key feature of successful COVID-19 exit strategies.

# Citation

**Ainslie KEC**, Walters CE, Fu H, Bhatia S, Wang H, Xi X, Baguelin M, Bhatt S, Boonyasiri A, Boyd O, Cattarino L, Ciavarella C, Cucunuba Z, Cuomo-Dannenburg G, Dighe A, Dorigatti I, van Elsland SL, FitzJohn R, Gaythorpe K, Ghani AC, Green W, Hamlet A, Hinsley W, Imai N, Jorgensen D, Knock E, Laydon D, Nedjati-Gilani G, Okell LC, Siveroni I, Thompson HA, Unwin HJT, Verity R, Vollmer M, Walker PGT, Wang Y, Watson OJ, Whittaker C, Winskill P, Donnelly CA, Ferguson NM, Riley S. Evidence of initial success for China exiting COVID-19 social distancing policy after achieving containment. Wellcome Open Res. 2020 Oct 1;5:81. PMID: 32500100; PMCID: PMC7236587. [\[DOI\]](https://doi.org/10.12688/wellcomeopenres.15843.2)
