---
title: 'Gene integrated set profile analysis: a context-based approach for inferring biological endpoints'
description: 'Nucleic Acids Res 44(7):e69.'
author: 'Jeanne Kowalski, Bhakti Dwivedi, Scott Newman, Jeffery M Switchenko, Rini Pauly, David A Gutman, Jyoti Arora, Khanjan Gandhi, Kylie Ainslie, Gregory Doho, Zhaohui Qin, Carlos S Moreno, Michael R Rossi, Paula M Vertino, Sagar Lonial, Leon Bernal-Mizrachi, Lawrence H Boise'
date: '2016-04-20'
doi: https://doi.org/10.1093/nar/gkv1503
categories: 
  - publication
---

# Abstract

The identification of genes with specific patterns of change (e.g. down-regulated and methylated) as phenotype drivers or samples with similar profiles for a given gene set as drivers of clinical outcome, requires the integration of several genomic data types for which an 'integrate by intersection' (IBI) approach is often applied. In this approach, results from separate analyses of each data type are intersected, which has the limitation of a smaller intersection with more data types. We introduce a new method, GISPA (Gene Integrated Set Profile Analysis) for integrated genomic analysis and its variation, SISPA (Sample Integrated Set Profile Analysis) for defining respective genes and samples with the context of similar, a priori specified molecular profiles. With GISPA, the user defines a molecular profile that is compared among several classes and obtains ranked gene sets that satisfy the profile as drivers of each class. With SISPA, the user defines a gene set that satisfies a profile and obtains sample groups of profile activity. Our results from applying GISPA to human multiple myeloma (MM) cell lines contained genes of known profiles and importance, along with several novel targets, and their further SISPA application to MM coMMpass trial data showed clinical relevance.

# Citation

Kowalski J, Dwivedi B, Newman S, Switchenko JM, Pauly R, Gutman DA, Arora J, Gandhi K, Ainslie K, Doho G, Qin Z, Moreno CS, Rossi MR, Vertino PM, Lonial S, Bernal-Mizrachi L, Boise LH. Gene integrated set profile analysis: a context-based approach for inferring biological endpoints. Nucleic Acids Res. 2016 Apr 20;44(7):e69. doi: 10.1093/nar/gkv1503.
