---
title: 'Anonymised and aggregated crowd level mobility data from mobile phones suggests that initial compliance with COVID-19 social distancing interventions was high and geographically consistent across the UK'
description: 'Wellcome Open Research 27:2101090'
author: Benjamin Jeffrey, Caroline E Walters, Kylie EC Ainslie, et al.
date: '2020-07-17'
doi: https://doi.org/10.12688/wellcomeopenres.15997.1
categories: 
  - publication
---

# Abstract

## **Background**

Since early March 2020, the COVID-19 epidemic across the United Kingdom has led to a range of social distancing policies, which have resulted in reduced mobility across different regions. Crowd level data on mobile phone usage can be used as a proxy for actual population mobility patterns and provide a way of quantifying the impact of social distancing measures on changes in mobility.\

## **Methods**

Here, we use two mobile phone-based datasets (anonymised and aggregated crowd level data from O2 and from the Facebook app on mobile phones) to assess changes in average mobility, both overall and broken down into high and low population density areas, and changes in the distribution of journey lengths.\

## **Results**

We show that there was a substantial overall reduction in mobility, with the most rapid decline on the 24th March 2020, the day after the Prime Minister's announcement of an enforced lockdown. The reduction in mobility was highly synchronized across the UK. Although mobility has remained low since 26th March 2020, we detect a gradual increase since that time. We also show that the two different datasets produce similar trends, albeit with some location-specific differences. We see slightly larger reductions in average mobility in high-density areas than in low-density areas, with greater variation in mobility in the high-density areas: some high-density areas eliminated almost all mobility.

## **Conclusions**

These analyses form a baseline from which to observe changes in behaviour in the UK as social distancing is eased and inform policy towards the future control of SARS-CoV-2 in the UK.

# Citation

Jeffrey B, Walters CE, **Ainslie KEC** *et al.* Anonymised and aggregated crowd level mobility data from mobile phones suggests that initial compliance with COVID-19 social distancing interventions was high and geographically consistent across the UK \[version 1; peer review: 2 approved\]. *Wellcome Open Res* 2020, **5**:170 [\[DOI\]](https://doi.org/10.12688/wellcomeopenres.15997.1)
