---
title: 'A Dynamic Model for Evaluation of the Bias of Influenza Vaccine Effectiveness Estimates From Observational Studies'
description: 'Am J Epidemiol 188(2):451-460.'
author: 'Kylie E C Ainslie, Meng Shi, Michael Haber, Walter A Orenstein'
date: '2019-02-1'
doi: https://doi.org/10.1093/aje/kwy240
categories: 
  - publication
---

# Abstract

Given that influenza vaccination is now widely recommended in the United States, observational studies based on patients with acute respiratory illness (ARI) remain as the only option to estimate influenza vaccine effectiveness (VE). We developed a dynamic probability model to evaluate bias of VE estimates from passive surveillance cohort, test-negative, and traditional case-control studies. The model includes 2 covariates (health status and health awareness) that might affect the probabilities of vaccination, developing ARI, and seeking medical care. Our results suggest that test-negative studies produce unbiased estimates of VE against medically attended influenza when: 1) Vaccination does not affect the probability of noninfluenza ARI; and 2) health status has the same effect on the probability of influenza and noninfluenza ARIs. The same estimate might be severely biased (i.e., estimated VE - true VE ≥ 0.20) for estimating VE against symptomatic influenza if the vaccine affects the probability of seeking care against influenza ARI. VE estimates from test-negative studies might also be severely biased for both outcomes of interest when vaccination affects the probability of noninfluenza ARI, but estimates from passive surveillance cohort studies are unbiased in this case. Finally, VE estimates from traditional case-control studies suffer from bias regardless of the source of bias.

# Citation

Ainslie KEC, Shi M, Haber M, Orenstein WA. A Dynamic Model for Evaluation of the Bias of Influenza Vaccine Effectiveness Estimates From Observational Studies. Am J Epidemiol. 2019 Feb 1;188(2):451-460. doi: 10.1093/aje/kwy240.
