project:
  type: website
  output-dir: docs

website:
  title: "Kylie Ainslie, PhD"
  repo-url: https://github.com/kylieainslie/kylieainslie.github.io
  twitter-card:
    creator: "@DrKAinslie"
    card-style: summary_large_image
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - about.qmd
      - research.qmd
      - publications.qmd
      - cv.qmd

format:
  html:
    theme:
      light: minty
      dark: slate
    css: styles.css
    toc: true

editor: visual

