project:
  type: website
  output-dir: docs

website:
  title: "Kylie Ainslie, PhD"
  repo-url: https://github.com/kylieainslie/spidr
  twitter-card:
    creator: "@DrKAinslie"
    card-style: summary_large_image
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

