project:
  type: website
  output-dir: docs

website:
  title: "Kylie Ainslie, PhD"
  repo-url: https://github.com/kylieainslie/kylieainslie.github.io
  twitter-card:
    creator: "@kylieainslie"
    card-style: summary_large_image
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Bluesky_Social_logo.svg/1200px-Bluesky_Social_logo.svg.png"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - about.qmd
      - research.qmd
      - publications.qmd
      - cv.qmd
      - text: Tutorials
        menu:
          - text: "Automated Pipelines with Maestro"
            href: tutorials/automation_with_maestro.qmd

format:
  html:
    theme:
      light: minty
      dark: slate
    css: styles.css
    toc: true

editor: visual

