project:
  type: website

website:
  title: "Kylie Ainslie, PhD"
  repo-url: https://github.com/kylieainslie/spidr
  twitter-card:
    creator: "@DrKAinslie"
    card-style: summary_large_image
  navbar:
    background: primary
    search: true
    left:
      left:
      - text: "Home"
        file: index.qmd
      - sidebar:about
      - sidebar:research
      - sidebar:publications

  sidebar:
    - id: about
      title: "About"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        # navigation items
        
    - id: Research
      title: "Research"
      contents:
        # navigation items
        
    - id: publications
      title: "Publications"
      contents:
        # navigation items


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

