---
title: "Research Projects"
editor: visual
---

------------------------------------------------------------------------

## Evaluation of WAning Vaccine Effectiveness (WAVE)

Information regarding decreasing VE is essential to optimally design booster vaccination campaigns with respect to the risk of outbreaks and whether repeated vaccination is cost-effective and ethical. The COVID-19 pandemic highlighted the lack of robust methods to: assess waning vaccine effectiveness, disentangle true from perceived waning, and identify determinants of waning. In this project, we aim to develop and rigorously compare methods to assess waning vaccine-induced protection (for vaccines such as those against pertussis, influenza, and COVID-19). Using these methods, we will analyze data from observational studies to estimate the rate of waning vaccine effectiveness and determine how individual characteristics influence rate of waning vaccine-induced protection.

#### Related publications

-   Haber, M., et al. Comparing statistical methods for detecting and estimating waning efficacy of rotavirus vaccines in developing countries. Hum Vaccin Immunother. 2021;17: 4632–4635. [link](https://pubmed.ncbi.nlm.nih.gov/34613877/)

## Modelling the impact of vaccination strategies

In this project, we use mathematical models of infectious disease transmission to determine the impact of vaccination strategies on disease spread. Specifically, we developed a deterministic age-structured compartmental model to compare different COVID-19 vaccination scenarios with respect to disease outcomes (e.g., infections, hospitalisations). This work also contributed to the [European Scenario Modelling Hub](https://covid19scenariohub.eu/).

#### Related publications

-   Ainslie, K. E. C., *et al*. A scenario modelling analysis to anticipate the impact of COVID-19 vaccination in adolescents and children on disease outcomes in the Netherlands, summer 2021. Euro Surveill. 2022;27(44):pii=2101090. [link](https://doi.org/10.2807/1560-7917.ES.2022.27.44.2101090)

-   Sherratt, K., *et al*. Characterising information gains and losses when collecting multiple epidemic model outputs. medRxiv 2024. [link](https://doi.org/10.1101/2023.07.05.23292245)

-   Ainslie, K. E. C. *et al.* The expected outcome of COVID-19 vaccination strategies. RIVM 2021. [link](https://www.rivm.nl/documenten/expected-outcome-of-covid-19-vaccination-strategies)

#### Related links

-   Transmission model code base: <https://github.com/kylieainslie/vacamole>

-   European scenario modelling hub: <https://github.com/european-modelling-hubs/covid19-scenario-hub-europe>

## Estimating the epidemiological characteristics of scabies

Scabies is a contagious skin disease caused by the infestation of the skin by the Sarcopes scabiei mite, causing an itchy rash. Scabies affects over 400 million people annually worldwide, and a rise in scabies cases has been observed in recent years throughout Western Europe. Despite the prevalence of scabies, some fundamental epidemiological characteristics of scabies infections have not been described. In this project, we use publicly available data on date of symptom onset during scabies outbreaks to estimate the mean serial interval, time between symptom onset in an infector and symptom onset in an infectee, of scabies infection. We also use weekly counts of scabies diagnoses from sentinel surveillance in the Netherlands from 2011-2023 to determine quantities related to the spread of scabies over time, namely, the time-varying reproduction number, growth rate, and basic reproduction number.

#### Related links

-   Ainslie, K. E. C. , M. Hooiveld, J. Wallinga. Estimation of the epidemiological characteristics of scabies. *(preprint)* 2025. [link](https://kylieainslie.github.io/mitey/articles/epidemiology_of_scabies.html)
-   `mitey` R package: <https://github.com/kylieainslie/mitey>
