---
title: 'Response to COVID-19 in South Korea and implications for lifting stringent interventions'
description: 'BMC Medicine 18(1): 1-11'
author: 'Amy Dighe, Lorenzo Cattarino, Gina Cuomo-Dannenburg, et al.'
date: '2021-12-01'
doi: https://doi.org/10.1186/s12916-020-01791-8
categories: 
  - publication
---

# Abstract

### Background

After experiencing a sharp growth in COVID-19 cases early in the pandemic, South Korea rapidly controlled transmission while implementing less stringent national social distancing measures than countries in Europe and the USA. This has led to substantial interest in their "test, trace, isolate" strategy. However, it is important to understand the epidemiological peculiarities of South Korea's outbreak and characterise their response before attempting to emulate these measures elsewhere.

### Methods

We systematically extracted numbers of suspected cases tested, PCR-confirmed cases, deaths, isolated confirmed cases, and numbers of confirmed cases with an identified epidemiological link from publicly available data. We estimated the time-varying reproduction number, *R~t~*, using an established Bayesian framework, and reviewed the package of interventions implemented by South Korea using our extracted data, plus published literature and government sources.

### Results

We estimated that after the initial rapid growth in cases, *R~t~* dropped below one in early April before increasing to a maximum of 1.94 (95%CrI, 1.64--2.27) in May following outbreaks in Seoul Metropolitan Region. By mid-June, *R~t~* was back below one where it remained until the end of our study (July 13th). Despite less stringent "lockdown" measures, strong social distancing measures were implemented in high-incidence areas and studies measured a considerable national decrease in movement in late February. Testing the capacity was swiftly increased, and protocols were in place to isolate suspected and confirmed cases quickly; however, we could not estimate the delay to isolation using our data. Accounting for just 10% of cases, individual case-based contact tracing picked up a relatively minor proportion of total cases, with cluster investigations accounting for 66%.

### Conclusions

Whilst early adoption of testing and contact tracing is likely to be important for South Korea's successful outbreak control, other factors including regional implementation of strong social distancing measures likely also contributed. The high volume of testing and the low number of deaths suggest that South Korea experienced a small epidemic relative to other countries. Caution is needed in attempting to replicate the South Korean response in populations with larger more geographically widespread epidemics where finding, testing, and isolating cases that are linked to clusters may be more difficult.

# Citation

Dighe, A., Cattarino, L., Cuomo-Dannenburg, G. *et al.* Response to COVID-19 in South Korea and implications for lifting stringent interventions. *BMC Med* **18**, 321 (2020). [\[DOI\]](https://doi.org/10.1186/s12916-020-01791-8)
