---
title: 'Challenges in estimating influenza vaccine effectiveness'
description: 'Expert Rev Vaccines 18(6):615-628'
author: 'Kylie E C Ainslie, Michael Haber, Walt A Orenstein'
date: '2019-05-31'
doi: https://doi.org/10.1080/14760584.2019.1622419
categories: 
  - publication
---

# Abstract

### Introduction
Influenza vaccination is regarded as the most effective way to prevent influenza infection. Due to the rapid genetic changes that influenza viruses undergo, seasonal influenza vaccines must be reformulated and re-administered annually necessitating the evaluation of influenza vaccine effectiveness (VE) each year. The estimation of influenza VE presents numerous challenges. 

### Areas Covered 
This review aims to identify, discuss, and, where possible, offer suggestions for dealing with the following challenges in estimating influenza VE: different outcomes of interest against which VE is estimated, study designs used to assess VE, sources of bias and confounding, repeat vaccination, waning immunity, population level effects of vaccination, and VE in at-risk populations. 

### Expert Opinion
The estimation of influenza VE has improved with surveillance networks, better understanding of sources of bias and confounding, and the implementation of advanced statistical methods. Future research should focus on better estimates of the indirect effects of vaccination, the biological effects of vaccination, and how vaccines interact with the immune system. Specifically, little is known about how influenza vaccination impacts an individual's infectiousness, how vaccines wane over time, and the impact of repeated vaccination.

# Citation
Ainslie KEC, Haber M, Orenstein WA. Challenges in estimating influenza vaccine effectiveness. Expert Rev Vaccines. 2019 Jun;18(6):615-628. [DOI](10.1080/14760584.2019.1622419)