---
title: 'Reduction in mobility and COVID-19 transmission'
description: 'Nature Communications 12: 1090'
author: 'Pierre Nouvellet, Sangeeta Bhatia, Anne Cori, Kylie EC Ainslie, Marc Baguelin, Samir Bhatt, Adhiratha Boonyasiri, Nicholas F Brazeau, Lorenzo Cattarino, Laura V Cooper, Helen Coupland, Zulma M Cucunuba, Gina Cuomo-Dannenburg, Amy Dighe, Bimandra A Djaafara, Ilaria Dorigatti, Oliver D Eales, Sabine L van Elsland, Fabricia F Nascimento, Richard G FitzJohn, Katy AM Gaythorpe, Lily Geidelberg, William D Green, Arran Hamlet, Katharina Hauck, Wes Hinsley, Natsuko Imai, Benjamin Jeffrey, Edward Knock, Daniel J Laydon, John A Lees, Tara Mangal, Thomas A Mellan, Gemma Nedjati-Gilani, Kris V Parag, Margarita Pons-Salort, Manon Ragonnet-Cronin, Steven Riley, H Juliette T Unwin, Robert Verity, Michaela AC Vollmer, Erik Volz, Patrick GT Walker, Caroline E Walters, Haowei Wang, Oliver J Watson, Charles Whittaker, Lilith K Whittles, Xiaoyue Xi, Neil M Ferguson, Christl A Donnelly'
date: '2021-02-17'
doi: https://doi.org/10.1038/s41467-021-21358-2
categories: 
  - publication
---

# Abstract

In response to the COVID-19 pandemic, countries have sought to control SARS-CoV-2 transmission by restricting population movement through social distancing interventions, thus reducing the number of contacts. Mobility data represent an important proxy measure of social distancing, and here, we characterise the relationship between transmission and mobility for 52 countries around the world. Transmission significantly decreased with the initial reduction in mobility in 73% of the countries analysed, but we found evidence of decoupling of transmission and mobility following the relaxation of strict control measures for 80% of countries. For the majority of countries, mobility explained a substantial proportion of the variation in transmissibility (median adjusted R-squared: 48%, interquartile range - IQR - across countries \[27--77%\]). Where a change in the relationship occurred, predictive ability decreased after the relaxation; from a median adjusted R-squared of 74% (IQR across countries \[49--91%\]) pre-relaxation, to a median adjusted R-squared of 30% (IQR across countries \[12--48%\]) post-relaxation. In countries with a clear relationship between mobility and transmission both before and after strict control measures were relaxed, mobility was associated with lower transmission rates after control measures were relaxed indicating that the beneficial effects of ongoing social distancing behaviours were substantial.

# Citation

Nouvellet, P., Bhatia, S., Cori, A. *et al.* Reduction in mobility and COVID-19 transmission. *Nat Commun* **12**, 1090 (2021). [\[DOI\]](https://doi.org/10.1038/s41467-021-21358-2)
