---
title: 'An open source tool to infer epidemiological and immunological dynamics from serological data: serosolver'
description: 'PLoS Comput Biol 16(5): e1007840'
author: 'James A. Hay, Amanda Minter, Kylie E. C. Ainslie, Justin Lessler, Bingyi Yang, Derek A. T. Cummings,Adam J. Kucharski, Steven Riley'
date: '2020-05-04'
doi: https://doi.org/10.1371/journal.pcbi.1007840
categories: 
  - publication
---

# Abstract

We present a flexible, open source R package designed to obtain biological and epidemiological insights from serological datasets. Characterising past exposures for multi-strain pathogens poses a specific statistical challenge: observed antibody responses measured in serological assays depend on multiple unobserved prior infections that produce cross-reactive antibody responses. We provide a general modelling framework to jointly infer infection histories and describe immune responses generated by these infections using antibody titres against current and historical strains. We do this by linking latent infection dynamics with a mechanistic model of antibody kinetics that generates expected antibody titres over time. Our aim is to provide a flexible package to identify infection histories that can be applied to a range of pathogens. We present two case studies to illustrate how our model can infer key immunological parameters, such as antibody titre boosting, waning and cross-reaction, as well as latent epidemiological processes such as attack rates and age-stratified infection risk.

# Author summary

Antibody levels can determine previous exposure to a pathogen and how likely individuals are to be infected in the future. However, antibody concentrations change over time, and some pathogens are continually evolving. In such cases, individuals may be infected and vaccinated multiple times when their pre-existing immunity fails, leading to a wide range of antibody profiles. Traditional approaches to analyse such data do not typically account for this. In addition, studies collecting antibody data may be designed differently, but are often underpinned by similar biological processes. We developed a statistical method and accompanying software package to better understand the immunology and epidemiology of these complex systems using serological data. We present two case studies to demonstrate how our software package, `serosolver`, can be applied to different settings: i) the epidemiology of the 2009 pandemic A/H1N1 influenza virus in Hong Kong and ii) historical patterns of A/H3N2 influenza infection in Guangzhou, China. These results demonstrate how modern analytical methods can reveal additional information from serological data that is otherwise missed using traditional approaches.

# Citation

Hay JA, Minter A, Ainslie KEC, Lessler J, Yang B, Cummings DAT, et al. (2020) An open source tool to infer epidemiological and immunological dynamics from serological data: serosolver. PLoS Comput Biol 16(5): e1007840. https://doi.org/10.1371/journal.pcbi.1007840

# Code

The `serosolver` `R` package is available at: <https://seroanalytics.github.io/serosolver/>. All data used in the manuscript analyses are available within the R package git repository at: <https://github.com/seroanalytics/serosolver/tree/master/inst/extdata>.
