---
title: "SARS-CoV-2 infection and vaccine effectiveness in England (REACT-1): a series of cross-sectional random community surveys"
description: 'The Lancet Respiratory Medicine 10(4):355-366'
author: Marc Chadeau-Hyam, Haowei Wang, Oliver Eales, David Haw, Barbara Bodinier, Matthew Whitaker, Caroline E Walters, Kylie EC Ainslie, Christina Atchison, Claudio Fronterre, Peter J Diggle, Andrew J Page, Alexander J Trotter, Deborah Ashby, Wendy Barclay, Graham Taylor, Graham Cooke, Helen Ward, Ara Darzi, Steven Riley, Christl A Donnelly, Paul Elliott
date: '2022'
doi: https://doi.org/10.1016/S2213-2600(21)00542-7
categories: 
  - publication
---

# Abstract

### Background

England has experienced a third wave of the COVID-19 epidemic since the end of May, 2021, coinciding with the rapid spread of the delta (B.1.617.2) variant, despite high levels of vaccination among adults. Vaccination rates (single dose) in England are lower among children aged 16--17 years and 12--15 years, whose vaccination in England commenced in August and September, 2021, respectively. We aimed to analyse the underlying dynamics driving patterns in SARS-CoV-2 prevalence during September, 2021, in England.

### Methods

The REal-time Assessment of Community Transmission-1 (REACT-1) study, which commenced data collection in May, 2020, involves a series of random cross-sectional surveys in the general population of England aged 5 years and older. Using RT-PCR swab positivity data from 100 527 participants with valid throat and nose swabs in round 14 of REACT-1 (Sept 9--27, 2021), we estimated community-based prevalence of SARS-CoV-2 and vaccine effectiveness against infection by combining round 14 data with data from round 13 (June 24 to July 12, 2021; n=172 862).

### Findings

During September, 2021, we estimated a mean RT-PCR positivity rate of 0·83% (95% CrI 0·76--0·89), with a reproduction number (R) overall of 1·03 (95% CrI 0·94--1·14). Among the 475 (62·2%) of 764 sequenced positive swabs, all were of the delta variant; 22 (4·63%; 95% CI 3·07--6·91) included the Tyr145His mutation in the spike protein associated with the AY.4 sublineage, and there was one Glu484Lys mutation. Age, region, key worker status, and household size jointly contributed to the risk of swab positivity. The highest weighted prevalence was observed among children aged 5--12 years, at 2·32% (95% CrI 1·96--2·73) and those aged 13--17 years, at 2·55% (2·11--3·08). The SARS-CoV-2 epidemic grew in those aged 5--11 years, with an R of 1·42 (95% CrI 1·18--1·68), but declined in those aged 18--54 years, with an R of 0·81 (0·68--0·97). At ages 18--64 years, the adjusted vaccine effectiveness against infection was 62·8% (95% CI 49·3--72·7) after two doses compared to unvaccinated people, for all vaccines combined, 44·8% (22·5--60·7) for the ChAdOx1 nCov-19 (Oxford--AstraZeneca) vaccine, and 71·3% (56·6--81·0) for the BNT162b2 (Pfizer--BioNTech) vaccine. In individuals aged 18 years and older, the weighted prevalence of swab positivity was 0·35% (95% CrI 0·31--0·40) if the second dose was administered up to 3 months before their swab but 0·55% (0·50--0·61) for those who received their second dose 3--6 months before their swab, compared to 1·76% (1·60--1·95) among unvaccinated individuals.

### Interpretation

In September, 2021, at the start of the autumn school term in England, infections were increasing exponentially in children aged 5--17 years, at a time when vaccination rates were low in this age group. In adults, compared to those who received their second dose less than 3 months ago, the higher prevalence of swab positivity at 3--6 months following two doses of the COVID-19 vaccine suggests an increased risk of breakthrough infections during this period. The vaccination programme needs to reach children as well as unvaccinated and partially vaccinated adults to reduce SARS-CoV-2 transmission and associated disruptions to work and education.

# Citation

Marc Chadeau-Hyam, Haowei Wang, Oliver Eales, David Haw, Barbara Bodinier, Matthew Whitaker, Caroline E Walters, Kylie EC Ainslie, Christina Atchison, Claudio Fronterre, Peter J Diggle, Andrew J Page, Alexander J Trotter, Deborah Ashby, Wendy Barclay, Graham Taylor, Graham Cooke, Helen Ward, Ara Darzi, Steven Riley, Christl A Donnelly, Paul Elliott. 2022. SARS-CoV-2 infection and vaccine effectiveness in England (REACT-1): a series of cross-sectional random community surveys. *The Lancet Respiratory Medicine* 10(4):355-366. [\[DOI\]](https://doi.org/10.1016/S2213-2600(21)00542-7)
