---
title: 'Reflections On Epidemiological Modeling To Inform Policy During The COVID-19 Pandemic In Western Europe, 2020-23'
description: 'Health Affairs (Millwood) 42(12):1630-1636'
author: 'Mark Jit, Kylie Ainslie, Christian Althaus, Constantino Caetano, Vittoria Colizza, Daniela Paolotti, Philippe Beutels, Lander Willem, John Edmunds, Baltazar Nunes, Sónia Namorado, Christel Faes, Nicola Low, Jacco Wallinga, Niel Hens'
date: '2023-12-01'
doi: https://doi.org/10.1377/hlthaff.2023.00688
categories: 
  - publication
---

# Abstract

We reflect on epidemiological modeling conducted throughout the COVID-19 pandemic in Western Europe, specifically in Belgium, France, Italy, the Netherlands, Portugal, Switzerland, and the United Kingdom. Western Europe was initially one of the worst-hit regions during the COVID-19 pandemic. Western European countries deployed a range of policy responses to the pandemic, which were often informed by mathematical, computational, and statistical models. Models differed in terms of temporal scope, pandemic stage, interventions modeled, and analytical form. This diversity was modulated by differences in data availability and quality, government interventions, societal responses, and technical capacity. Many of these models were decisive to policy making at key junctures, such as during the introduction of vaccination and the emergence of the Alpha, Delta, and Omicron variants. However, models also faced intense criticism from the press, other scientists, and politicians around their accuracy and appropriateness for decision making. Hence, evaluating the success of models in terms of accuracy and influence is an essential task. Modeling needs to be supported by infrastructure for systems to collect and share data, model development, and collaboration between groups, as well as two-way engagement between modelers and both policy makers and the public.

# Citation
Jit M, Ainslie K, Althaus C, Caetano C, Colizza V, Paolotti D, Beutels P, Willem L, Edmunds J, Nunes B, Namorado S, Faes C, Low N, Wallinga J, Hens N. Reflections On Epidemiological Modeling To Inform Policy During The COVID-19 Pandemic In Western Europe, 2020-23. Health Aff (Millwood). 2023 Dec;42(12):1630-1636. [DOI](10.1377/hlthaff.2023.00688).