---
title: 'The impact of COVID-19 and strategies for mitigation and suppression in low- and middle-income countries'
description: 'Science 369(6502):413-422'
author: 'Patrick G T Walker*, Charles Whittaker*, Oliver J Watson*, Marc Baguelin, Peter Winskill, Arran Hamlet, Bimandra A Djafaara, Zulma Cucunubá, Daniela Olivera Mesa, Will Green, Hayley Thompson, Shevanthi Nayagam, Kylie E C Ainslie, Sangeeta Bhatia, Samir Bhatt, Adhiratha Boonyasiri, Olivia Boyd, Nicholas F Brazeau, Lorenzo Cattarino, Gina Cuomo-Dannenburg, Amy Dighe, Christl A Donnelly, Ilaria Dorigatti, Sabine L van Elsland, Rich FitzJohn, Han Fu, Katy A M Gaythorpe, Lily Geidelberg, Nicholas Grassly, David Haw, Sarah Hayes, Wes Hinsley, Natsuko Imai, David Jorgensen, Edward Knock, Daniel Laydon , Swapnil Mishra, Gemma Nedjati-Gilani, Lucy C Okell, H Juliette Unwin, Robert Verity, Michaela Vollmer, Caroline E Walters, Haowei Wang, Yuanrong Wang, Xiaoyue Xi, David G Lalloo, Neil M Ferguson, Azra C Ghani
* contributed equally'
date: '2020-07-24'
doi: https://doi.org/10.1126/science.abc0035
categories: 
  - publication
---

# Abstract

The ongoing coronavirus disease 2019 (COVID-19) pandemic poses a severe threat to public health worldwide. We combine data on demography, contact patterns, disease severity, and health care capacity and quality to understand its impact and inform strategies for its control. Younger populations in lower-income countries may reduce overall risk, but limited health system capacity coupled with closer intergenerational contact largely negates this benefit. Mitigation strategies that slow but do not interrupt transmission will still lead to COVID-19 epidemics rapidly overwhelming health systems, with substantial excess deaths in lower-income countries resulting from the poorer health care available. Of countries that have undertaken suppression to date, lower-income countries have acted earlier. However, this will need to be maintained or triggered more frequently in these settings to keep below available health capacity, with associated detrimental consequences for the wider health, well-being, and economies of these countries.

# Citation

Walker PGT, Whittaker C, Watson OJ, Baguelin M, Winskill P, Hamlet A, Djafaara BA, Cucunubá Z, Olivera Mesa D, Green W, Thompson H, Nayagam S, Ainslie KEC, Bhatia S, Bhatt S, Boonyasiri A, Boyd O, Brazeau NF, Cattarino L, Cuomo-Dannenburg G, Dighe A, Donnelly CA, Dorigatti I, van Elsland SL, FitzJohn R, Fu H, Gaythorpe KAM, Geidelberg L, Grassly N, Haw D, Hayes S, Hinsley W, Imai N, Jorgensen D, Knock E, Laydon D, Mishra S, Nedjati-Gilani G, Okell LC, Unwin HJ, Verity R, Vollmer M, Walters CE, Wang H, Wang Y, Xi X, Lalloo DG, Ferguson NM, Ghani AC. The impact of COVID-19 and strategies for mitigation and suppression in low- and middle-income countries. Science. 2020 Jul 24;369(6502):413-422. [DOI](10.1126/science.abc0035)
