---
title: 'Association of COVID-19 vaccination with duration of hospitalization in older adults in Hong Kong'
description: 'Vaccine 42(9):2385-2393'
author: 'Dongxuan Chen, Benjamin J Cowling, Kylie E C Ainslie, Yun Lin, Jessica Y Wong, Eric H Y Lau, Peng Wu, Joshua Nealon'
date: '2024-04-02'
doi: https://doi.org/10.1016/j.vaccine.2024.02.074
categories: 
  - publication
---

# Abstract

### Background

The association between COVID-19 vaccination and length of hospital stay may provide further insight into vaccination benefits, but few studies have investigated such associations in detail. We aimed to investigate the association between COVID-19 vaccination and length of hospital stay in COVID-19 patients during Omicron waves in Hong Kong, and explore potential predictors.

### Methods

This retrospective cohort study was conducted on local patients aged ≥60 years who were admitted due to COVID-19 infection in Hong Kong in 2022, from 1 February to 22 November, and with 28 days of follow-up since admission. The exposure was either not vaccinated; or having received 2/3/4 doses of CoronaVac (Sinovac); or 2/3/4 doses of BNT162b2 (BioNTech/Fosun Pharma/Pfizer). Length of stay in hospital was the main outcome. Accelerated failure time models were used to quantify variation in hospital stay for vaccinated compared with unvaccinated patients, accounting for age, sex, comorbidity, type of vaccine and number of doses received, care home residence and admission timing; stratified by age groups and epidemic waves.

### Results

This study included 32,398 patients aged 60 years and above for main analysis, their median (IQR) age was 79 (71-87) years, 53% were men, and 40% were unvaccinated. The patients were stratified by confirmation prior to or since 23 May 2022, resulting in a sample size of 15,803 and 16,595 in those two waves respectively. Vaccinated patients were found to have 13-39% shorter hospital stay compared to unvaccinated patients. More vaccine doses received were associated with shorter hospital stay, and BNT162b2 recipients had slightly shorter hospital stays than CoronaVac recipients.

### Conclusions

Vaccination was associated with reduced hospital stay in breakthrough infections. Increased vaccination uptake in older adults may improve hospital bed turnover and public health outcomes especially during large community epidemics.

# Citation

Chen D, Cowling BJ, Ainslie KEC, Lin Y, Wong JY, Lau EHY, Wu P, Nealon J. Association of COVID-19 vaccination with duration of hospitalization in older adults in Hong Kong. Vaccine. 2024 Apr 2;42(9):2385-2393. [DOI]( 10.1016/j.vaccine.2024.02.074)
