---
title: 'Is annual vaccination best? A modelling study of influenza vaccination strategies in children'
description: 'Vaccine 40(21):2940-2948'
author: Kylie E C Ainslie, Steven Riley
date: '2022-05-09'
doi: https://doi.org/10.1016/j.vaccine.2022.03.065
categories: 
  - publication
---

# Abstract

### Introduction

Annual vaccination of children against influenza is a key component of vaccination programs in many countries. However, past infection and vaccination may affect an individual's susceptibility to infection. Little research has evaluated whether annual vaccination is the best strategy. Using the United Kingdom as our motivating example, we developed a framework to assess the impact of different childhood vaccination strategies, specifically annual and biennial (every other year), on attack rate and expected number of infections.

### Methods and findings

We present a multi-annual, individual-based, stochastic, force of infection model that accounts for individual exposure histories and disease/vaccine dynamics influencing susceptibility. We simulate birth cohorts that experience yearly [influenza epidemics](https://www.sciencedirect.com/topics/medicine-and-dentistry/seasonal-influenza "Learn more about influenza epidemics from ScienceDirect's AI-generated Topic Pages") and follow them until age 18 to determine attack rates and the number of infections during childhood. We perform simulations under baseline conditions, with an assumed [vaccination coverage](https://www.sciencedirect.com/topics/medicine-and-dentistry/vaccination-coverage "Learn more about vaccination coverage from ScienceDirect's AI-generated Topic Pages") of 44%, to compare annual vaccination to no and biennial vaccination. We relax our baseline assumptions to explore how our model assumptions impact vaccination program performance.

At baseline, we observed less than half the number of infections between the ages 2 and 10 under annual vaccination in children who had been vaccinated at least half the time compared to no vaccination. When averaged over all ages 0--18, the number of infections under annual vaccination was 2.07 (2.06, 2.08) compared to 2.63 (2.62, 2.64) under no vaccination, and 2.38 (2.37, 2.40) under biennial vaccination. When we introduced a penalty for repeated exposures, we observed a decrease in the difference in infections between the vaccination strategies. Specifically, the difference in childhood infections under biennial compared to annual vaccination decreased from 0.31 to 0.04 as exposure penalty increased.

### Conclusion

Our results indicate that while annual vaccination averts more childhood infections than biennial vaccination, this difference is small. Our work confirms the value of annual vaccination in children, even with modest vaccination coverage, but also shows that similar benefits of vaccination may be obtained by implementing a biennial vaccination program.

# Author Summary

Many countries include annual vaccination of children against influenza in their vaccination programs. In the United Kingdom (UK), annual vaccination of children aged of 2 to 10 against influenza is recommended. However, little research has evaluated whether annual vaccination is the best strategy, while accounting for how past infection and vaccination may affect an individual's susceptibility to infection in the current influenza season. Prior work has suggested that there may be a negative effect of repeated vaccination. In this work we developed a stochastic, individual-based model to assess the impact of repeated vaccination strategies on childhood infections. Specifically, we first compare annual vaccination to no vaccination and then annual vaccination to biennial (every other year) vaccination. We use the UK as our motivating example. We found that an annual vaccination strategy resulted in the fewest childhood infections, followed by biennial vaccination. The difference in number of childhood infections between the different vaccination strategies decreased when we introduced a penalty for repeated exposures. Our work confirms the value of annual vaccination in children, but also shows that similar benefits of vaccination can be obtained by implementing a biennial vaccination program, particularly when there is a negative effect of repeated vaccinations.

# Citation

**Ainslie, K. E. C.** and S. Riley. 2022. Is annual vaccination best? A modelling study of influenza vaccination in children. *Vaccine* 40(21):2940-2948. [\[DOI\]](https://doi.org/10.1016/j.vaccine.2022.03.065)
