---
title: 'Characterising information gains and losses when collecting multiple epidemic model outputs'
description: 'Epidemics 47:100765'
author: Katharine Sherratt, Ajitesh Srivastava, Kylie E C Ainslie, David E Singh, Aymar Cublier, Maria Cristina Marinescu, Jesus Carretero, Alberto Cascajo Garcia, Nicolas Franco, Lander Willem, Steven Abrams, Christel Faes, Philippe Beutels, Niel Hens, Sebatian M端ller, Billy Charlton, Ricardo Ewert, Sydney Paltra, Christian Rakow, Jakob Rehmann, Tim Conrad, Christof Sch端tte, Kai Nagel, Sam Abbott, Rok Grah, Rene Niehus, Bastian Prasse, Frank Sandmann, Sebastian Funk
date: '2024-03-27'
doi: https://doi.org/10.1016/j.epidem.2024.100765
categories: 
  - publication
---

# Abstract

## Background
Collaborative comparisons and combinations of epidemic models are used as policy-relevant evidence during epidemic outbreaks. In the process of collecting multiple model projections, such collaborations may gain or lose relevant information. Typically, modellers contribute a probabilistic summary at each time-step. We compared this to directly collecting simulated trajectories. We aimed to explore information on key epidemic quantities; ensemble uncertainty; and performance against data, investigating potential to continuously gain information from a single cross-sectional collection of model results.

## Methods
We compared projections from the European COVID-19 Scenario Modelling Hub. Five teams modelled incidence in Belgium, the Netherlands, and Spain. We compared July 2022 projections by incidence, peaks, and cumulative totals. We created a probabilistic ensemble drawn from all trajectories, and compared to ensembles from a median across each model's quantiles, or a linear opinion pool. We measured the predictive accuracy of individual trajectories against observations, using this in a weighted ensemble. We repeated this sequentially against increasing weeks of observed data. We evaluated these ensembles to reflect performance with varying observed data.

## Results
By collecting modelled trajectories, we showed policy-relevant epidemic characteristics. Trajectories contained a right-skewed distribution well represented by an ensemble of trajectories or a linear opinion pool, but not models' quantile intervals. Ensembles weighted by performance typically retained the range of plausible incidence over time, and in some cases narrowed this by excluding some epidemic shapes.

## Conclusions
We observed several information gains from collecting modelled trajectories rather than quantile distributions, including potential for continuously updated information from a single model collection. The value of information gains and losses may vary with each collaborative effort's aims, depending on the needs of projection users. Understanding the differing information potential of methods to collect model projections can support the accuracy, sustainability, and communication of collaborative infectious disease modelling efforts.

# Citation
Sherratt K, Srivastava A, Ainslie K, Singh DE, Cublier A, Marinescu MC, Carretero J, Garcia AC, Franco N, Willem L, Abrams S, Faes C, Beutels P, Hens N, M端ller S, Charlton B, Ewert R, Paltra S, Rakow C, Rehmann J, Conrad T, Sch端tte C, Nagel K, Abbott S, Grah R, Niehus R, Prasse B, Sandmann F, Funk S. Characterising information gains and losses when collecting multiple epidemic model outputs. Epidemics. 2024 Jun;47:100765. [DOI](https://doi.org/10.1016/j.epidem.2024.100765)
