---
title: 'Exponential growth, high prevalence of SARS-CoV-2, and vaccine effectiveness associated with the Delta variant'
description: 'Science, 375, 6587, (1406-1411)'
author: 'Paul Elliott, David Haw, Haowei Wang, Oliver Eales, Caroline E Walters, Kylie EC Ainslie, Christina Atchison, Claudio Fronterre, Peter J Diggle, Andrew J Page, Alexander J Trotter, Sophie J Prosolek, COVID-19 Genomics UK (COG-UK) Consortium, Deborah Ashby, Christl A Donnelly, Wendy Barclay, Graham Taylor, Graham Cooke, Helen Ward, Ara Darzi, Steven Riley'
date: '2021-12-17'
doi: 10.1126/science.abl9551
categories: 
  - publication
---

# Vaccination and disease

## **Vaccination and disease**

The United Kingdom has high rates of vaccination for severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2), exceeding 80% of adults. As immunity wanes and social distancing is relaxed, how are rates of illness and severe disease affected by more infectious variants? Elliott *et al*. used reverse transcription PCR data from the REACT-1 study, which showed exponential transmission as the Alpha variant (B.1.1.7) was replaced by the Delta variant (B.1.617.2). After adjusting for age and other variables, vaccine effectiveness for the new variant averaged 55% in June and July of 2020. Despite the slower growth of the pandemic in the summer, it looks as if increased indoor mixing in the autumn will sustain transmission of the Delta variant despite high levels of adult vaccination. ---CA

# Structured Abstract

### **Background**

The prevalence of severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) infection continues to drive rates of illness and hospitalizations despite high levels of vaccination, with the proportion of cases caused by the Delta lineage increasing in many populations. As vaccination programs roll out globally and social distancing is relaxed, future SARS-CoV-2 trends are uncertain.

### **Methods**

The Real-time Assessment of Community Transmission--1 (REACT-1) study has been tracking the spread of the COVID-19 pandemic in England since May 2020. The study involves obtaining a self-administered throat and nose swab for reverse transcription polymerase chain reaction (RT-PCR) from \~100,000 or more people during 2 to 3 weeks each month, based on random samples of the population in England at ages 5 years and above. As well as information on swab positivity, we collect demographic and other data on potential risk factors and (since January 2021) vaccination history. Prevalence estimates are weighted to be representative of the population of England as a whole. Here, we analyzed prevalence trends and their drivers using RT-PCR swab positivity data from REACT-1 round 12 (between 20 May and 7 June 2021) and round 13 (between 24 June and 12 July 2021). Response rates, defined as the percentage of invitees from whom we received a valid swab result, were 20.4% across all rounds and 13.4% and 11.7% for rounds 12 and 13, respectively.

### **Results**

We observed sustained exponential growth as the third wave in England took hold, with reproduction number *R* estimated at 1.44 (95% credible interval 1.20, 1.73) in round 12 and 1.19 (1.06, 1.32) in round 13, corresponding to an average doubling time of 11 days (7, 23 days) in round 12 and 25 days (15, \>50 days) in round 13. This resulted in an increase in average weighted prevalence from 0.15% (0.12%, 0.18%) in round 12 (based on 135 positives out of 108,911 valid swabs) to 0.63% (0.57%, 0.69%) in round 13 (527 positives out of 98,233). The rapid growth across and within rounds appears to have been driven by complete replacement of the Alpha variant by Delta, and by the high prevalence in younger, less-vaccinated age groups: Among those aged 13 to 17 years, we observed an increase in weighted prevalence by a factor of 9 between round 12 \[0.16% (0.08%, 0.31%)\] and round 13 \[1.56% (1.25%, 1.95%)\]. In round 13, weighted prevalence among those who reported being unvaccinated \[1.21% (1.03%, 1.41%)\] was greater than for those who reported having had two doses of vaccine \[0.40% (0.34%, 0.48%)\] by a factor of 3; however, 44% of infections occurred in doubly vaccinated individuals, reflecting imperfect vaccine effectiveness (VE) against infection after two doses despite high overall levels of vaccination.

Among participants aged 18 to 64 years, on the basis of self-reported vaccination status, we estimated VE against infection (adjusted for age, sex, region, ethnicity, and index of multiple deprivation) of 49% (95% confidence interval 22%, 67%) in round 13, rising to 58% (33%, 73%) when only strong positives \[cycle threshold (Ct) values below 27\] were considered. For the same age group, we estimated adjusted VE of 59% (23%, 78%) against symptomatic infection---that is, among those reporting one or more common COVID-19 symptoms in the month prior to testing (fever, loss or change of sense of smell or taste, new persistent cough). Ethnicity, household size, and local levels of deprivation, in addition to age, jointly contributed to the risk of higher prevalence of swab positivity.

### **Conclusion**

From the end of May to the beginning of July 2021 in England, where there was a highly successful vaccination campaign with high vaccine uptake, infections were increasing exponentially---driven by the Delta variant---with high infection prevalence among younger, unvaccinated individuals. Despite slower growth (or level or declining prevalence) during summer 2021 in the Northern Hemisphere, increased mixing in the presence of the Delta variant likely explains renewed growth that occurred in autumn 2021, even in populations with high levels of vaccination.

# Abstract

Severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) infections were rising during early summer 2021 in many countries as a result of the Delta variant. We assessed reverse transcription polymerase chain reaction swab positivity in the Real-time Assessment of Community Transmission--1 (REACT-1) study in England. During June and July 2021, we observed sustained exponential growth with an average doubling time of 25 days, driven by complete replacement of the Alpha variant by Delta and by high prevalence at younger, less-vaccinated ages. Prevalence among unvaccinated people \[1.21% (95% credible interval 1.03%, 1.41%)\] was three times that among double-vaccinated people \[0.40% (95% credible interval 0.34%, 0.48%)\]. However, after adjusting for age and other variables, vaccine effectiveness for double-vaccinated people was estimated at between \~50% and \~60% during this period in England. Increased social mixing in the presence of Delta had the potential to generate sustained growth in infections, even at high levels of vaccination.

# Citation

Paul Elliott, David Haw, Haowei Wang, Oliver Eales, Caroline E Walters, **Kylie EC Ainslie**, Christina Atchison, Claudio Fronterre, Peter J Diggle, Andrew J Page, Alexander J Trotter, Sophie J Prosolek, COVID-19 Genomics UK (COG-UK) Consortium, Deborah Ashby, Christl A Donnelly, Wendy Barclay, Graham Taylor, Graham Cooke, Helen Ward, Ara Darzi, Steven Riley. Exponential growth, high prevalence of SARS-CoV-2, and vaccine effectiveness associated with the Delta variant, *Science*, **375**, 6587, (1406-1411), (2022). [\[DOI\]](https://doi.org/10.1126/science.abl9551)
